name: Build
on:
  push:
    branches:
      - main # or the name of your main branch

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Roblox-File-Format
        run: git clone https://github.com/CloneTrooper1019/Roblox-File-Format.git ../Roblox-File-Format
        
      - name: ValveKeyValue
        run: git clone https://github.com/SteamDatabase/ValveKeyValue.git ../ValveKeyValue
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        shell: powershell
        run: |
          cd ../ValveKeyValue
          dir
          dotnet build
          dotnet publish
          dir ../
          dir
          dir build
